// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// EncodeResponse is an autogenerated mock type for the EncodeResponse type
type EncodeResponse struct {
	mock.Mock
}

// Encode provides a mock function with given fields: _a0, _a1
func (_m *EncodeResponse) Encode(_a0 http.ResponseWriter, _a1 interface{}) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, interface{}) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
