// Code generated by mockery v1.0.0. DO NOT EDIT.

package comment

import mock "github.com/stretchr/testify/mock"

// MockCommentInterface is an autogenerated mock type for the CommentInterface type
type MockCommentInterface struct {
	mock.Mock
}

// GetComments provides a mock function with given fields:
func (_m *MockCommentInterface) GetComments() ([]Comment, error) {
	ret := _m.Called()

	var r0 []Comment
	if rf, ok := ret.Get(0).(func() []Comment); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Comment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
