// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import comment "grab/internal/comment"
import mock "github.com/stretchr/testify/mock"

// CommentsWorker is an autogenerated mock type for the CommentsWorker type
type CommentsWorker struct {
	mock.Mock
}

// GetComments provides a mock function with given fields:
func (_m *CommentsWorker) GetComments() ([]comment.Comment, error) {
	ret := _m.Called()

	var r0 []comment.Comment
	if rf, ok := ret.Get(0).(func() []comment.Comment); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]comment.Comment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
