// Code generated by mockery v1.0.0. DO NOT EDIT.

package mimeGenerate

import mock "github.com/stretchr/testify/mock"

// MockMimeGenerate is an autogenerated mock type for the MimeGenerate type
type MockMimeGenerate struct {
	mock.Mock
}

// Generate provides a mock function with given fields: orgObj
func (_m MockMimeGenerate) Generate(orgObj interface{}) (MimeResult, error) {
	ret := _m.Called(orgObj)

	var r0 MimeResult
	if rf, ok := ret.Get(0).(func(interface{}) MimeResult); ok {
		r0 = rf(orgObj)
	} else {
		r0 = ret.Get(0).(MimeResult)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(orgObj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGenerateType provides a mock function with given fields:
func (_m MockMimeGenerate) GetGenerateType() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}