// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	"grab/internal/bootcamp/model"

	"github.com/stretchr/testify/mock"
)

// BlogService is an autogenerated mock type for the BlogService type
type BlogService struct {
	mock.Mock
}

// GetPostWithComments provides a mock function with given fields:
func (_m *BlogService) GetPostWithComments() (*[]model.PostWithComments, error) {
	ret := _m.Called()

	var r0 *[]model.PostWithComments
	if rf, ok := ret.Get(0).(func() *[]model.PostWithComments); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]model.PostWithComments)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
