// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "bathien/assignment/entity"
import mock "github.com/stretchr/testify/mock"

// DataGetter is an autogenerated mock type for the DataGetter type
type DataGetter struct {
	mock.Mock
}

// GetComments provides a mock function with given fields:
func (_m *DataGetter) GetComments() ([]entity.Comment, error) {
	ret := _m.Called()

	var r0 []entity.Comment
	if rf, ok := ret.Get(0).(func() []entity.Comment); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Comment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPosts provides a mock function with given fields:
func (_m *DataGetter) GetPosts() ([]entity.Post, error) {
	ret := _m.Called()

	var r0 []entity.Post
	if rf, ok := ret.Get(0).(func() []entity.Post); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Post)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
